# -*- coding: utf-8 -*-
"""01_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZfJnvGrGdAsJE3CCPX74mmKt5x8uhLT

# 01 - Análise Exploratória dos Dados

Este notebook tem como objetivo realizar a análise exploratória inicial das bases brutas `application_record.csv` e `credit_record.csv`.

Nesta etapa, serão avaliadas a estrutura das bases, tipos de variáveis, valores ausentes, duplicidades, distribuição das principais variáveis cadastrais e comportamento do histórico mensal de crédito.

As bases serão carregadas como `app_raw` e `credit_raw` para deixar claro que representam os dados originais, antes dos tratamentos realizados no notebook de pré-processamento.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

app_raw = pd.read_csv("application_record.csv")
credit_raw = pd.read_csv("credit_record.csv")

"""A base `application_record` contém os dados cadastrais dos clientes, enquanto a base `credit_record` contém o histórico mensal de crédito.

A primeira análise mostra a quantidade de linhas e colunas, os tipos de dados e uma amostra inicial dos registros. Essa etapa é importante para entender a estrutura dos dados antes de qualquer transformação.
"""

print("Application record:")
print(app_raw.shape)
display(app_raw.head())
app_raw.info()

print("\nCredit record:")
print(credit_raw.shape)
display(credit_raw.head())
credit_raw.info()

"""## Análise de valores ausentes

Foi realizada a verificação de valores ausentes nas bases brutas `application_record` e `credit_record`.

Na base `application_record`, observou-se que apenas a coluna `OCCUPATION_TYPE` possui valores ausentes. As demais colunas da base cadastral não apresentam valores nulos.

Na base `credit_record`, não foram identificados valores ausentes nas colunas `ID`, `MONTHS_BALANCE` e `STATUS`.

Esse resultado indica que o principal ponto de atenção em relação a valores ausentes está na variável de ocupação dos clientes. No notebook de pré-processamento, essa coluna deverá ser tratada de forma específica para evitar perda excessiva de registros.
"""

print("Valores ausentes em application_record:")
display(app_raw.isna().sum().sort_values(ascending=False))

print("\nValores ausentes em credit_record:")
display(credit_raw.isna().sum().sort_values(ascending=False))

qtd_nulos_occupation = app_raw["OCCUPATION_TYPE"].isna().sum()
perc_nulos_occupation = app_raw["OCCUPATION_TYPE"].isna().mean() * 100

print("Quantidade de nulos em OCCUPATION_TYPE:", qtd_nulos_occupation)
print(f"Percentual de nulos em OCCUPATION_TYPE: {perc_nulos_occupation:.2f}%")

"""## Análise de duplicidades

Foi realizada a verificação de duplicidades nas bases brutas.

Na base `application_record`, não foram encontradas linhas completamente duplicadas. No entanto, foram identificadas ocorrências de IDs duplicados. Como essa base representa dados cadastrais, espera-se que cada `ID` corresponda a um único cliente. Portanto, esses casos devem ser investigados no pré-processamento.

Na base `credit_record`, não foram encontradas linhas duplicadas. A base possui 45.985 clientes únicos e 1.048.575 registros no total. A diferença entre esses números é esperada, pois a base está no nível cliente-mês, ou seja, um mesmo cliente pode aparecer várias vezes ao longo do histórico mensal de crédito.
"""

# Verificação de duplicidades nas bases brutas

print("Linhas duplicadas em application_record:")
print(app_raw.duplicated().sum())

print("\nIDs duplicados em application_record:")
print(app_raw["ID"].duplicated().sum())

print("\nLinhas duplicadas em credit_record:")
print(credit_raw.duplicated().sum())

print("\nIDs únicos em credit_record:")
print(credit_raw["ID"].nunique())

print("\nTotal de registros em credit_record:")
print(credit_raw.shape[0])

"""## Distribuição das variáveis categóricas

Foi analisada a distribuição das principais variáveis categóricas da base `application_record`.

Observou-se que a base possui maior quantidade de registros na categoria `F` em `CODE_GENDER`. Em relação à posse de bens, a maior parte dos clientes não possui carro (`FLAG_OWN_CAR = N`), enquanto a maioria possui imóvel (`FLAG_OWN_REALTY = Y`).

Quanto ao perfil socioeconômico, a categoria de renda mais frequente é `Working`, seguida por `Commercial associate` e `Pensioner`. Em escolaridade, predomina `Secondary / secondary special`. Em estado civil, a categoria mais frequente é `Married`, e em tipo de moradia há forte predominância de `House / apartment`.

A coluna `OCCUPATION_TYPE` apresenta grande quantidade de valores ausentes. Entre as ocupações informadas, as categorias mais frequentes são `Laborers`, `Core staff`, `Sales staff` e `Managers`. Esse resultado reforça que a variável `OCCUPATION_TYPE` deverá receber atenção específica na etapa de pré-processamento.
"""

categorical_cols = [
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE",
    "OCCUPATION_TYPE"
]

for col in categorical_cols:
    print(f"\nDistribuição de {col}:")
    display(app_raw[col].value_counts(dropna=False))

"""## Visualização das variáveis categóricas

Após a análise das frequências absolutas das variáveis categóricas, foram gerados gráficos de barras para facilitar a comparação visual entre as categorias.

O gráfico de barras é adequado para variáveis categóricas porque permite observar rapidamente quais categorias são mais frequentes e quais aparecem em menor quantidade. Esse tipo de gráfico facilita a identificação de desbalanceamentos, predominância de determinados grupos e possíveis categorias raras.

Para variáveis como `CODE_GENDER`, `FLAG_OWN_CAR`, `FLAG_OWN_REALTY`, `NAME_INCOME_TYPE`, `NAME_EDUCATION_TYPE`, `NAME_FAMILY_STATUS` e `NAME_HOUSING_TYPE`, foi utilizado o gráfico de barras horizontal com contagem de registros por categoria. A orientação horizontal foi escolhida porque melhora a leitura dos nomes das categorias, especialmente quando os rótulos são longos.

No caso de `OCCUPATION_TYPE`, a variável possui muitas categorias e também apresenta valores ausentes. Para evitar um gráfico excessivamente carregado, foram visualizadas apenas as dez categorias mais frequentes. Essa escolha permite destacar os principais grupos ocupacionais e, ao mesmo tempo, manter o gráfico legível.

A visualização confirma os padrões observados nas tabelas de frequência. A base apresenta maior concentração em algumas categorias específicas, como `Working` em tipo de renda, `Secondary / secondary special` em escolaridade, `Married` em estado civil e `House / apartment` em tipo de moradia.

Também se observa que `OCCUPATION_TYPE` possui grande volume de valores ausentes, reforçando a necessidade de tratamento específico dessa variável na etapa de pré-processamento.
"""

# Gráficos de barras para variáveis categóricas.
# Esse tipo de gráfico é adequado para comparar a frequência de categorias.
# A orientação horizontal melhora a leitura dos rótulos.

cols_plot = [
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE"
]

for col in cols_plot:
    plt.figure(figsize=(8, 4))
    sns.countplot(
        data=app_raw,
        y=col,
        order=app_raw[col].value_counts().index
    )
    plt.title(f"Distribuição de {col}")
    plt.xlabel("Quantidade")
    plt.ylabel(col)
    plt.show()

# OCCUPATION_TYPE possui muitas categorias.
# Para manter a visualização legível, foram exibidas apenas as 10 categorias mais frequentes.

top_occupation = app_raw["OCCUPATION_TYPE"].value_counts(dropna=False).head(10)

plt.figure(figsize=(8, 5))
sns.barplot(
    x=top_occupation.values,
    y=top_occupation.index.astype(str)
)
plt.title("Top 10 categorias de OCCUPATION_TYPE")
plt.xlabel("Quantidade")
plt.ylabel("Ocupação")
plt.show()

"""## Investigação de possíveis valores extremos

Após a análise estatística inicial, foram investigados possíveis valores extremos nas variáveis `AMT_INCOME_TOTAL`, `CNT_CHILDREN` e `CNT_FAM_MEMBERS`.

A análise por percentis mostrou que a maior parte dos registros possui valores relativamente concentrados. No caso de `AMT_INCOME_TOTAL`, 99,9% dos registros possuem renda anual de até aproximadamente 990.000, enquanto o valor máximo observado é 6.750.000. Isso indica a presença de valores muito acima do padrão geral da base.

Para `CNT_CHILDREN`, observa-se que 99,9% dos registros possuem até 4 filhos, mas o valor máximo é 19. De forma semelhante, em `CNT_FAM_MEMBERS`, 99,9% dos registros possuem até 6 membros familiares, enquanto o valor máximo é 20.

Ao visualizar os maiores registros de `CNT_CHILDREN` e `CNT_FAM_MEMBERS`, percebe-se que os valores são coerentes entre si, pois os registros com maior quantidade de filhos também apresentam maior tamanho familiar. Ainda assim, esses valores são raros e devem ser avaliados com cautela.

Nesta etapa de análise exploratória, os valores extremos não serão removidos ou modificados. O objetivo da EDA é identificar padrões, levantar hipóteses e orientar decisões para o pré-processamento. A decisão sobre manter, transformar, agrupar ou limitar esses valores será registrada posteriormente no notebook `02_preprocessamento.ipynb`.

Para investigar os possíveis valores extremos, foram utilizados percentis e ordenações decrescentes das variáveis.

Os percentis ajudam a entender até que ponto os valores da base estão concentrados. Por exemplo, comparar o percentil 99,9% com o valor máximo permite identificar se o maior valor está muito distante do restante da distribuição.

Além disso, foram visualizados os maiores registros de renda, quantidade de filhos e tamanho da família. Essa análise permite verificar se os valores extremos aparecem isolados, se possuem coerência com outras variáveis e se podem representar possíveis erros ou apenas casos raros.

"""

numeric_cols = [
    "CNT_CHILDREN",
    "AMT_INCOME_TOTAL",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED",
    "CNT_FAM_MEMBERS"
]

app_raw[numeric_cols].describe()

app_raw[["AMT_INCOME_TOTAL", "CNT_CHILDREN", "CNT_FAM_MEMBERS"]].quantile(
    [0.90, 0.95, 0.99, 0.995, 0.999]
)

app_raw.sort_values("AMT_INCOME_TOTAL", ascending=False)[
    ["ID", "AMT_INCOME_TOTAL", "NAME_INCOME_TYPE", "OCCUPATION_TYPE"]
].head(20)

app_raw.sort_values("CNT_FAM_MEMBERS", ascending=False)[
    ["ID", "CNT_CHILDREN", "CNT_FAM_MEMBERS", "NAME_FAMILY_STATUS"]
].head(20)

app_raw.sort_values("CNT_CHILDREN", ascending=False)[
    ["ID", "CNT_CHILDREN", "CNT_FAM_MEMBERS", "NAME_FAMILY_STATUS"]
].head(20)

"""## Visualização das variáveis temporais

Para analisar as variáveis `AGE_YEARS` e `EMPLOYED_YEARS`, foram utilizados histogramas e boxplots.

O histograma foi escolhido porque é uma das formas mais adequadas de visualizar variáveis numéricas contínuas. Esse tipo de gráfico permite observar como os valores estão distribuídos ao longo da população, identificando regiões de maior concentração, dispersão, assimetrias e possíveis padrões na distribuição dos dados.

Além das barras do histograma, foi incluída uma curva de densidade (`Kernel Density Estimation - KDE`). Essa linha suavizada representa uma estimativa da distribuição dos dados e auxilia na identificação do formato geral da distribuição, tornando mais fácil visualizar tendências que podem não ser percebidas apenas pelas barras de frequência.

Também foram utilizados boxplots para complementar a análise. O boxplot resume a distribuição por meio da mediana, quartis e amplitude dos dados, além de destacar possíveis valores extremos. Esse tipo de gráfico é útil para identificar observações que se afastam significativamente do comportamento predominante da base.

A utilização conjunta de histogramas e boxplots permite compreender tanto a forma geral da distribuição quanto a presença de possíveis valores extremos, fornecendo uma visão mais completa das variáveis analisadas.

## Interpretação dos resultados

A distribuição da idade mostra que a maior parte dos clientes está concentrada entre aproximadamente 30 e 55 anos, com média de 43,8 anos e mediana de 42,8 anos. Os valores observados são compatíveis com o perfil esperado de solicitantes de crédito e não foram identificadas idades fora de uma faixa plausível.

Em relação ao tempo de emprego, observa-se uma concentração de clientes com poucos anos de vínculo empregatício, acompanhada por uma cauda à direita formada por indivíduos com carreiras mais longas. A média de aproximadamente 7,2 anos é superior à mediana de 5,3 anos, indicando a presença dessa assimetria.

Os boxplots não indicam valores impossíveis após a remoção do valor especial identificado em `DAYS_EMPLOYED`, embora existam registros com longos períodos de emprego, o que é esperado em uma população com ampla faixa etária.
"""

import numpy as np

app_eda = app_raw.copy()

app_eda["AGE_YEARS"] = (
    -app_eda["DAYS_BIRTH"] / 365
).round(1)

app_eda["EMPLOYED_YEARS"] = np.where(
    app_eda["DAYS_EMPLOYED"] == 365243,
    np.nan,
    -app_eda["DAYS_EMPLOYED"] / 365
)

app_eda["EMPLOYED_YEARS"] = (
    app_eda["EMPLOYED_YEARS"]
    .round(1)
)

app_eda[[
    "AGE_YEARS",
    "EMPLOYED_YEARS"
]].describe()

plt.figure(figsize=(8,4))

sns.histplot(
    app_eda["AGE_YEARS"],
    bins=30,
    kde=True
)

plt.title("Distribuição da Idade")
plt.xlabel("Idade (anos)")
plt.ylabel("Frequência")

plt.show()

plt.figure(figsize=(8,4))

sns.histplot(
    app_eda["EMPLOYED_YEARS"].dropna(),
    bins=30,
    kde=True
)

plt.title("Distribuição do Tempo de Emprego")
plt.xlabel("Tempo de emprego (anos)")
plt.ylabel("Frequência")

plt.show()

fig, axes = plt.subplots(
    1,
    2,
    figsize=(12,4)
)

sns.boxplot(
    x=app_eda["AGE_YEARS"],
    ax=axes[0]
)

axes[0].set_title("Boxplot da Idade")

sns.boxplot(
    x=app_eda["EMPLOYED_YEARS"],
    ax=axes[1]
)

axes[1].set_title("Boxplot do Tempo de Emprego")

plt.tight_layout()
plt.show()

"""## Análise da variável STATUS

A coluna `STATUS` representa a situação mensal de pagamento de cada cliente na base `credit_record`.

Foram analisadas as distribuições absoluta e percentual dos diferentes status para compreender o comportamento geral do histórico de crédito disponível.

Para essa análise foi utilizado um gráfico de barras, pois a variável é categórica. Esse tipo de visualização facilita a comparação entre categorias e permite identificar rapidamente quais situações de pagamento são mais frequentes.

Observa-se que a maior parte dos registros está concentrada nos status `C`, `0` e `X`.

- `C` representa pagamentos quitados no mês;
- `0` representa atraso entre 1 e 29 dias;
- `X` indica ausência de empréstimo naquele mês.

Os demais status representam atrasos mais severos e aparecem com frequência muito reduzida. Em especial, os status `2`, `3`, `4` e `5`, associados a atrasos iguais ou superiores a 60 dias, representam uma parcela pequena da base.

Esse resultado sugere que eventos de inadimplência grave são relativamente raros no nível mensal, antecipando o desbalanceamento observado posteriormente na construção da variável alvo.
"""

credit_raw["STATUS"].value_counts().sort_index()

(
    credit_raw["STATUS"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
).round(2)

plt.figure(figsize=(8,4))

sns.countplot(
    data=credit_raw,
    x="STATUS",
    order=sorted(credit_raw["STATUS"].unique())
)

plt.title("Distribuição da variável STATUS")
plt.xlabel("STATUS")
plt.ylabel("Quantidade de registros")

plt.show()

"""## Análise da variável MONTHS_BALANCE

A coluna `MONTHS_BALANCE` representa o mês de referência de cada registro em relação ao momento atual.

De acordo com a documentação da base, o valor `0` representa o mês mais recente disponível, enquanto os valores negativos representam meses anteriores. Por exemplo, `-1` corresponde ao mês anterior, `-2` a dois meses antes e assim sucessivamente.

Foi utilizado um histograma para visualizar a distribuição temporal dos registros. Esse tipo de gráfico é adequado para variáveis numéricas contínuas, pois permite observar a concentração das observações ao longo do período analisado e identificar possíveis padrões de distribuição.

O histograma mostra um crescimento gradual da quantidade de registros à medida que os meses se aproximam do período mais recente. Esse comportamento sugere que parte dos clientes possui histórico mais curto, enquanto outros apresentam períodos de observação mais longos.

A análise estatística indica que a base contém registros entre os meses `-60` e `0`, correspondendo a aproximadamente cinco anos de histórico de crédito. A mediana igual a `-17` indica que metade dos registros está concentrada nos 17 meses mais recentes da base.
"""

credit_raw["MONTHS_BALANCE"].describe()

print("Mês mais antigo:", credit_raw["MONTHS_BALANCE"].min())
print("Mês mais recente:", credit_raw["MONTHS_BALANCE"].max())

plt.figure(figsize=(8,4))

sns.histplot(
    credit_raw["MONTHS_BALANCE"])

"""## Quantidade de meses por cliente

Como a base `credit_record` está estruturada no nível cliente-mês, cada cliente pode possuir diferentes quantidades de registros ao longo do tempo.

Para investigar essa característica foi calculada a quantidade de meses observados para cada cliente.

Foi utilizado um histograma para visualizar a distribuição da quantidade de registros por cliente. Esse tipo de gráfico é adequado para variáveis numéricas porque permite identificar regiões de maior concentração, dispersão e assimetrias na distribuição.

Observa-se que os clientes possuem diferentes quantidades de histórico disponível. A média é de aproximadamente 22,8 meses por cliente, enquanto a mediana é de 19 meses. O menor histórico observado possui apenas 1 mês, enquanto o maior possui 61 meses.

A distribuição apresenta assimetria à direita, indicando que clientes com períodos muito longos de observação são menos frequentes que clientes com histórico mais curto.

Esse resultado é relevante para o problema de crédito, pois clientes com maior quantidade de meses observados possuem mais oportunidades de apresentar eventos de atraso. Portanto, o tamanho do histórico disponível deve ser considerado na interpretação da variável alvo construída posteriormente.
"""

meses_por_cliente = (
    credit_raw
    .groupby("ID")["MONTHS_BALANCE"]
    .count()
)

meses_por_cliente.describe()

plt.figure(figsize=(8,4))

sns.histplot(
    meses_por_cliente,
    bins=30,
    kde=True
)

plt.title("Quantidade de meses de histórico por cliente")
plt.xlabel("Meses observados")
plt.ylabel("Quantidade de clientes")

plt.show()

"""## Principais insights da análise exploratória

A análise exploratória permitiu compreender a estrutura e as principais características das bases `application_record` e `credit_record`.

Os principais achados foram:

- A base cadastral apresenta poucos problemas de qualidade de dados, sendo que a principal variável com valores ausentes é `OCCUPATION_TYPE`.
- Foram identificados IDs duplicados em `application_record`, indicando a necessidade de tratamento antes da integração com outras bases.
- As variáveis categóricas mostram predominância de clientes com renda do tipo `Working`, escolaridade `Secondary / secondary special`, estado civil `Married` e moradia do tipo `House / apartment`.
- Foram identificados valores extremos em variáveis como renda anual, quantidade de filhos e tamanho da família. Esses registros não foram removidos nesta etapa, sendo reservada para o pré-processamento a decisão sobre eventuais transformações.
- A população analisada é composta predominantemente por adultos em idade economicamente ativa, com média aproximada de 44 anos.
- O tempo de emprego apresenta distribuição assimétrica, com concentração em períodos mais curtos e alguns clientes com longos históricos profissionais.
- Na base `credit_record`, a maior parte dos registros está concentrada nos status `C`, `0` e `X`, enquanto eventos de inadimplência grave são relativamente raros.
- O histórico de crédito disponível cobre até 60 meses de observação, porém os clientes possuem diferentes quantidades de meses registrados.
- A quantidade de histórico varia consideravelmente entre os clientes, fator que deve ser considerado na construção e interpretação da variável alvo.

Esses resultados forneceram subsídios para as decisões adotadas posteriormente no notebook de pré-processamento e para o desenvolvimento dos modelos de classificação de risco de crédito.
"""