# -*- coding: utf-8 -*-
"""02_preprocessamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUctHaIoXclt7nLKZyATsk7d9sCNEOEn

Exploração inicial das bases: verificação da quantidade de linhas e colunas, tipos de dados e primeiras observações.
"""

import pandas as pd

app = pd.read_csv("application_record.csv")
credit = pd.read_csv("credit_record.csv")

print("Application record:")
print(app.shape)
display(app.head())
print(app.info())

print("\nCredit record:")
print(credit.shape)
display(credit.head())
print(credit.info())

"""Verificação de valores ausentes e registros duplicados nas bases application_record e credit_record."""

# Valores ausentes
print("Nulos em application_record:")
print(app.isna().sum().sort_values(ascending=False))

print("\nNulos em credit_record:")
print(credit.isna().sum().sort_values(ascending=False))

# Duplicados
print("Linhas duplicadas em application_record:", app.duplicated().sum())
print("IDs duplicados em application_record:", app["ID"].duplicated().sum())

print("Linhas duplicadas em credit_record:", credit.duplicated().sum())
print("IDs únicos em credit_record:", credit["ID"].nunique())

app.duplicated().sum()

app["ID"].duplicated().sum()

ids_duplicados_app = app[app["ID"].duplicated(keep=False)].sort_values("ID")

ids_duplicados_app

ids_duplicados_app["ID"].nunique()

ids_duplicados_app.shape

# Identificar IDs duplicados
ids_duplicados = app.loc[app["ID"].duplicated(keep=False), "ID"].unique()

# Remover todos os registros com IDs duplicados
app = app[~app["ID"].isin(ids_duplicados)].copy()

# Conferir se ainda existem IDs duplicados
print("IDs duplicados após tratamento:", app["ID"].duplicated().sum())
print("Formato da base após tratamento:", app.shape)

"""## Tratamento de IDs duplicados em `application_record`

Foi identificada a presença de IDs duplicados na base `application_record`. Ao analisar esses registros, observou-se que as linhas com o mesmo `ID` apresentavam informações cadastrais conflitantes, como diferenças em sexo, renda, estado civil, número de filhos e tamanho da família.

Como o `ID` será utilizado como chave para unir a base cadastral com a variável alvo, manter esses registros poderia gerar duplicações e inconsistências na base final. Dessa forma, optou-se por remover todos os registros associados a IDs duplicados, preservando apenas clientes com cadastro único na base.

## Tratamento de valores ausentes em `OCCUPATION_TYPE`

Após o tratamento dos IDs duplicados, foi analisada a presença de valores ausentes na coluna `OCCUPATION_TYPE`. Antes de aplicar qualquer preenchimento, os registros com ocupação ausente foram investigados em conjunto com outras variáveis, como `NAME_INCOME_TYPE`.

Como esses registros ainda possuíam informações relevantes em outras colunas e a ausência de ocupação representava uma parcela importante da base, optou-se por não remover essas linhas.
"""

app.isna().sum().sort_values(ascending=False)

app["OCCUPATION_TYPE"].value_counts(dropna=False)

app[app["OCCUPATION_TYPE"].isna()]["NAME_INCOME_TYPE"].value_counts()

"""Os valores ausentes em `OCCUPATION_TYPE` foram preenchidos com a categoria `Unknown`. Essa abordagem preserva os registros na base e permite que a ausência de ocupação seja tratada como uma informação categórica durante a análise e a modelagem."""

app["OCCUPATION_TYPE"] = app["OCCUPATION_TYPE"].fillna("Unknown")

app.isna().sum().sort_values(ascending=False)

"""## Tratamento das variáveis representadas em dias

As colunas `DAYS_BIRTH` e `DAYS_EMPLOYED` estavam representadas em dias. Para facilitar a interpretação, `DAYS_BIRTH` foi convertida para idade aproximada em anos, criando a variável `AGE_YEARS`.

A coluna `DAYS_EMPLOYED` foi analisada separadamente, pois contém o valor especial `365243`, que não representa um tempo real de emprego. Esse valor foi sinalizado por meio da variável `EMPLOYED_SPECIAL_VALUE`, substituído por `NA` em `DAYS_EMPLOYED_TREATED` e utilizado para criar a variável `EMPLOYED_YEARS`.
"""

import pandas as pd
import numpy as np

# 1. Criar idade em anos
app["AGE_YEARS"] = (-app["DAYS_BIRTH"] / 365).round(1)

# 2. Contar quantas vezes aparece o valor especial 365243 em DAYS_EMPLOYED
qtd_special_value = (app["DAYS_EMPLOYED"] == 365243).sum()
print("Quantidade de registros com DAYS_EMPLOYED = 365243:", qtd_special_value)

# 3. Criar flag para o valor especial de DAYS_EMPLOYED
app["EMPLOYED_SPECIAL_VALUE"] = (app["DAYS_EMPLOYED"] == 365243).astype(int)

# 4. Criar versão tratada de DAYS_EMPLOYED
app["DAYS_EMPLOYED_TREATED"] = app["DAYS_EMPLOYED"].replace(365243, pd.NA)

# 5. Criar tempo de emprego em anos
app["EMPLOYED_YEARS"] = (
    -pd.to_numeric(app["DAYS_EMPLOYED_TREATED"], errors="coerce") / 365
).round(1)

# 6. Converter Y/N para 1/0
# np.where evita o FutureWarning do replace e mantém o código simples.
# A condição considera "Y", 1 e "1" como sim, o que torna a célula segura
# caso ela seja executada mais de uma vez.
app["FLAG_OWN_CAR"] = np.where(
    app["FLAG_OWN_CAR"].isin(["Y", 1, "1"]),
    1,
    0
)

app["FLAG_OWN_REALTY"] = np.where(
    app["FLAG_OWN_REALTY"].isin(["Y", 1, "1"]),
    1,
    0
)

# 7. Conferir conversão das variáveis binárias
print("\nDistribuição de FLAG_OWN_CAR:")
print(app["FLAG_OWN_CAR"].value_counts(dropna=False))

print("\nDistribuição de FLAG_OWN_REALTY:")
print(app["FLAG_OWN_REALTY"].value_counts(dropna=False))

app[[
    "DAYS_BIRTH",
    "AGE_YEARS",
    "DAYS_EMPLOYED",
    "DAYS_EMPLOYED_TREATED",
    "EMPLOYED_YEARS",
    "EMPLOYED_SPECIAL_VALUE"
]].head(10)

app.isna().sum().sort_values(ascending=False)

app[[
    "DAYS_EMPLOYED",
    "DAYS_EMPLOYED_TREATED",
    "EMPLOYED_YEARS",
    "EMPLOYED_SPECIAL_VALUE"
]].head(10)

app.loc[app["DAYS_EMPLOYED"] > 0, "DAYS_EMPLOYED"].value_counts()

app.shape

"""## Verificação de consistência do tratamento de `DAYS_EMPLOYED`

Foi realizada uma verificação de consistência após o tratamento da coluna `DAYS_EMPLOYED`.

O valor especial `365243` foi identificado na base e tratado separadamente. Após o tratamento, a quantidade de registros marcados com `EMPLOYED_SPECIAL_VALUE = 1` deve coincidir com a quantidade de valores ausentes em `DAYS_EMPLOYED_TREATED` e `EMPLOYED_YEARS`.

Como os totais coincidiram, o tratamento foi considerado consistente.
"""

print("Quantidade de 365243 em DAYS_EMPLOYED:")
print((app["DAYS_EMPLOYED"] == 365243).sum())

print("\nQuantidade de 1 em EMPLOYED_SPECIAL_VALUE:")
print(app["EMPLOYED_SPECIAL_VALUE"].sum())

print("\nNulos em DAYS_EMPLOYED_TREATED:")
print(app["DAYS_EMPLOYED_TREATED"].isna().sum())

print("\nNulos em EMPLOYED_YEARS:")
print(app["EMPLOYED_YEARS"].isna().sum())

"""## Resumo da limpeza inicial da base `application_record`

Nesta etapa, foi realizada a limpeza inicial da base `application_record`.

Primeiramente, foram avaliadas as dimensões da base, os tipos de dados, os valores ausentes e a existência de registros duplicados. Foi identificada a presença de IDs duplicados com informações cadastrais conflitantes. Como o `ID` será utilizado como chave para unir a base cadastral com a variável alvo, optou-se por remover todos os registros associados a IDs duplicados.

Em seguida, foi analisada a coluna `OCCUPATION_TYPE`, que apresentava valores ausentes em quantidade relevante. Como esses registros ainda possuíam informações úteis em outras colunas, os valores ausentes foram preenchidos com a categoria `Unknown`.

Também foram criadas variáveis mais interpretáveis a partir das colunas em dias. A coluna `DAYS_BIRTH` foi convertida para idade em anos (`AGE_YEARS`). Já a coluna `DAYS_EMPLOYED` foi tratada separadamente por apresentar o valor especial `365243`, que não representa um tempo real de emprego. Esse valor foi substituído por `NA` em `DAYS_EMPLOYED_TREATED` e sinalizado pela variável `EMPLOYED_SPECIAL_VALUE`. Em seguida, foi criada a variável `EMPLOYED_YEARS`.

Por fim, as variáveis binárias `FLAG_OWN_CAR` e `FLAG_OWN_REALTY` foram convertidas de `Y/N` para `1/0`.
"""

print("Formato final da base app:")
print(app.shape)

print("\nIDs duplicados em app após tratamento:")
print(app["ID"].duplicated().sum())

print("\nValores nulos em app após tratamento:")
print(app.isna().sum().sort_values(ascending=False))

print("Formato da base credit:")
print(credit.shape)

print("\nPrimeiras linhas:")
display(credit.head())

print("\nInformações da base:")
credit.info()

# Valores ausentes na base credit_record
print("Nulos em credit_record:")
print(credit.isna().sum().sort_values(ascending=False))

# Investigar registros com STATUS ausente
credit[credit["STATUS"].isna()]

# Investigar registros com MONTHS_BALANCE inválido
credit[credit["MONTHS_BALANCE"] == "-"]

# Remover linha problemática e criar cópia segura
credit = credit.loc[credit["MONTHS_BALANCE"] != "-"].copy()

# Converter MONTHS_BALANCE para inteiro
credit["MONTHS_BALANCE"] = credit["MONTHS_BALANCE"].astype(int)

# Conferir novamente os nulos e tipos
print("Nulos em credit_record após tratamento:")
print(credit.isna().sum().sort_values(ascending=False))

print("\nInformações da base credit_record após tratamento:")
credit.info()

credit.isna().sum()

# 0 = 1 a 29 dias de atraso
# 1 = 30 a 59 dias de atraso
# 2 = 60 a 89 dias de atraso
# 3 = 90 a 119 dias de atraso
# 4 = 120 a 149 dias de atraso
# 5 = mais de 150 dias de atraso ou dívida baixada
# C = pago naquele mês
# X = sem empréstimo naquele mês

credit["STATUS"].value_counts().sort_index()

# Calcula a distribuição percentual de cada STATUS.
# normalize=True divide a contagem de cada categoria pelo total de registros.
# Multiplicamos por 100 para mostrar o resultado em porcentagem.
(credit["STATUS"].value_counts(normalize=True).sort_index() * 100).round(2)

"""## Análise da distribuição da coluna `STATUS`

A coluna `STATUS` representa a situação mensal de pagamento de cada cliente. Foi analisada a distribuição absoluta e percentual dos status para entender a frequência de cada situação de pagamento na base.

Observou-se que a maior parte dos registros está concentrada nos status `C`, `0` e `X`. O status `C` representa pagamentos quitados no mês, `0` representa atraso entre 1 e 29 dias, e `X` indica ausência de empréstimo no mês.

Os status associados a atrasos mais graves (`2`, `3`, `4` e `5`) aparecem com baixa frequência no nível mensal. Esse resultado indica que eventos de inadimplência grave são relativamente raros, o que pode gerar desbalanceamento ao construir a variável alvo.
"""

credit["MONTHS_BALANCE"].describe()

print("Mês mais antigo:", credit["MONTHS_BALANCE"].min())
print("Mês mais recente:", credit["MONTHS_BALANCE"].max())

"""## Análise da coluna `MONTHS_BALANCE`

A coluna `MONTHS_BALANCE` representa o mês do registro em relação ao mês atual.
De acordo com a documentação, o valor `0` corresponde ao mês atual, `-1` ao mês anterior, `-2` a dois meses atrás, e assim sucessivamente.

Após a limpeza inicial, a coluna foi analisada estatisticamente. Observou-se que os valores variam de `-60` a `0`, indicando que a base possui registros de até 60 meses anteriores ao mês atual, ou aproximadamente cinco anos de histórico.

A mediana da coluna é `-17`, indicando que metade dos registros está concentrada até cerca de 17 meses antes do mês atual. Essa informação é relevante porque clientes podem ter diferentes quantidades de histórico disponíveis, o que pode influenciar a construção da variável alvo.
"""

meses_por_cliente = credit.groupby("ID")["MONTHS_BALANCE"].count()

meses_por_cliente.describe()

meses_por_cliente.head()

"""## Quantidade de meses por cliente

Como a base `credit_record` está no nível cliente-mês, um mesmo cliente pode aparecer em várias linhas, cada uma representando um mês de histórico.

Foi calculada a quantidade de registros mensais disponíveis para cada `ID`. Observou-se que os clientes possuem diferentes tamanhos de histórico, ou seja, alguns clientes têm poucos meses registrados, enquanto outros possuem um período de observação maior.

Essa variação é importante porque clientes com mais meses de histórico tiveram mais oportunidades de apresentar atraso. Portanto, a quantidade de meses observados pode influenciar a construção e a interpretação da variável alvo.
"""

credit.duplicated(subset=["ID", "MONTHS_BALANCE"]).sum()

"""## Verificação de duplicidade por cliente e mês

Como a base `credit_record` está no nível cliente-mês, foi verificado se existiam registros duplicados para a combinação `ID` e `MONTHS_BALANCE`.

O resultado foi igual a zero, indicando que não há clientes com mais de um registro no mesmo mês.
Portanto, cada linha da base representa de forma única a situação de pagamento de um cliente em um determinado mês.
"""

# Criar indicador de mês com atraso grave
# STATUS 2, 3, 4 e 5 representam atrasos de 60 dias ou mais
credit["BAD_MONTH"] = credit["STATUS"].isin(["2", "3", "4", "5"]).astype(int)

credit["BAD_MONTH"].value_counts()

(credit["BAD_MONTH"].value_counts(normalize=True) * 100).round(2)

"""## Criação da variável auxiliar `BAD_MONTH`

A partir da coluna `STATUS`, foi criada a variável auxiliar `BAD_MONTH`, indicando se determinado registro mensal representa um atraso grave.

Foram considerados como atraso grave os status `2`, `3`, `4` e `5`, que correspondem a atrasos iguais ou superiores a 60 dias. Dessa forma, registros com esses status receberam valor `1`, enquanto os demais receberam valor `0`.

Após a criação da variável, foi verificada sua distribuição absoluta e percentual. Observou-se que os meses com atraso grave representam uma parcela pequena da base, confirmando que eventos de inadimplência grave são raros no nível mensal.
"""

target = credit.groupby("ID")["BAD_MONTH"].max().reset_index()

target = target.rename(columns={"BAD_MONTH": "TARGET_BAD"})

target.head()

target["TARGET_BAD"].value_counts()

(target["TARGET_BAD"].value_counts(normalize=True) * 100).round(2)

"""## Criação da variável alvo `TARGET_BAD`

A variável alvo foi criada a partir da coluna auxiliar `BAD_MONTH`. Como `BAD_MONTH` indica se determinado mês teve atraso grave, foi necessário consolidar essa informação no nível do cliente.

Para isso, os registros foram agrupados por `ID`, utilizando o valor máximo de `BAD_MONTH`. Dessa forma, se o cliente apresentou pelo menos um mês com atraso grave, recebeu `TARGET_BAD = 1`; caso contrário, recebeu `TARGET_BAD = 0`.

Após a criação da variável alvo, foi verificada sua distribuição absoluta e percentual. Observou-se forte desbalanceamento, com proporção muito maior de clientes classificados como bons pagadores do que maus pagadores.
"""

# Criar conjuntos de IDs para comparar as bases
ids_app = set(app["ID"])
ids_target = set(target["ID"])

# Verificar interseção entre app e target
print("Clientes em app:", len(ids_app))
print("Clientes em target:", len(ids_target))
print("Clientes em ambas:", len(ids_app.intersection(ids_target)))
print("Clientes em app sem target:", len(ids_app - ids_target))
print("Clientes em target sem app:", len(ids_target - ids_app))

"""## Junção das bases `application_record` e `target`

Antes de unir as bases, foi verificada a interseção entre os IDs da base cadastral (`app`) e os IDs da variável alvo (`target`).

Observou-se que nem todos os clientes da base cadastral possuem histórico de crédito, e nem todos os clientes com histórico de crédito possuem cadastro disponível na base `application_record`. Por esse motivo, foi utilizado um `merge` do tipo `inner`, mantendo apenas os clientes presentes nas duas bases.

Essa decisão garante que a base final contenha, para cada cliente, tanto as variáveis explicativas quanto a variável alvo `TARGET_BAD`, permitindo seguir para as próximas etapas de análise exploratória e modelagem.
"""

# Criar base final com clientes presentes nas duas bases
df = app.merge(target, on="ID", how="inner")

print("Formato da base final:", df.shape)
display(df.head())

print("\nDistribuição da variável alvo na base final:")
print(df["TARGET_BAD"].value_counts())

print("\nDistribuição percentual da variável alvo na base final:")
print((df["TARGET_BAD"].value_counts(normalize=True) * 100).round(2))

print("\nValores nulos na base final:")
print(df.isna().sum().sort_values(ascending=False))

print("\nIDs duplicados na base final:")
print(df["ID"].duplicated().sum())

"""## Base final para análise e modelagem

Após a criação da variável alvo `TARGET_BAD`, foi realizada a junção entre a base cadastral tratada (`app`) e a base de alvo (`target`) utilizando a coluna `ID`.

Foi utilizado um `merge` do tipo `inner`, mantendo apenas os clientes presentes nas duas bases. A base final resultante possui 36.457 registros e 23 colunas.

A distribuição da variável alvo mostrou forte desbalanceamento: a maior parte dos clientes foi classificada como bom pagador (`TARGET_BAD = 0`), enquanto uma pequena parcela foi classificada como mau pagador (`TARGET_BAD = 1`).

Após a junção, foi verificado que não existem IDs duplicados na base final. Também foi realizada a análise de valores ausentes. Os únicos nulos restantes estão nas colunas `DAYS_EMPLOYED_TREATED` e `EMPLOYED_YEARS`, o que é esperado, pois correspondem aos registros em que `DAYS_EMPLOYED` apresentava o valor especial `365243`.
"""

print("Nulos em EMPLOYED_YEARS:")
print(df["EMPLOYED_YEARS"].isna().sum())

print("\nRegistros com EMPLOYED_SPECIAL_VALUE = 1:")
print(df["EMPLOYED_SPECIAL_VALUE"].sum())

print("\nTratamento consistente?")
print(df["EMPLOYED_YEARS"].isna().sum() == df["EMPLOYED_SPECIAL_VALUE"].sum())

"""## Preparação final para modelagem

Após a análise exploratória dos dados, foram realizadas etapas adicionais de preparação da base para a fase de modelagem.

A primeira etapa consistiu na criação da variável `LOG_INCOME`, obtida por meio da transformação logarítmica da renda anual (`AMT_INCOME_TOTAL`). Durante a análise exploratória foi observado que a distribuição da renda apresenta forte assimetria à direita, com poucos clientes possuindo rendas muito superiores ao restante da população. A transformação logarítmica reduz o impacto desses valores extremos sem removê-los da base, preservando a informação e tornando a distribuição mais adequada para determinados algoritmos de classificação.

Em seguida, foi realizado o tratamento final da variável `EMPLOYED_YEARS`. Durante o pré-processamento inicial, os registros associados ao valor especial `365243` em `DAYS_EMPLOYED` foram convertidos para valores ausentes e sinalizados por meio da variável `EMPLOYED_SPECIAL_VALUE`.

Como esses registros representam uma condição específica já identificada e documentada, os valores ausentes de `EMPLOYED_YEARS` foram substituídos por `-1`. Esse valor foi escolhido por não representar um tempo de emprego real, permitindo diferenciar esses casos dos demais registros sem perder informação.

Após essas transformações, foi realizada uma nova verificação de valores ausentes para garantir que todas as variáveis utilizadas na etapa de modelagem estivessem completas.
"""

# Transformação logarítmica da renda
df["LOG_INCOME"] = np.log1p(df["AMT_INCOME_TOTAL"])

# Tratamento do valor especial de tempo de emprego
df["EMPLOYED_YEARS"] = df["EMPLOYED_YEARS"].fillna(-1)

# Conferência final dos valores ausentes
print(df.isna().sum().sort_values(ascending=False))

"""## Remoção de variáveis redundantes

Após a preparação final para modelagem, foi realizada uma avaliação das variáveis disponíveis na base com o objetivo de identificar colunas redundantes.

Algumas variáveis foram criadas durante o processo de tratamento apenas para facilitar a transformação dos dados e não agregam informação adicional em relação às variáveis derivadas produzidas posteriormente.

A variável `AGE_YEARS` representa a mesma informação presente em `DAYS_BIRTH`, porém em uma escala mais interpretável. Da mesma forma, `EMPLOYED_YEARS` representa o tempo de emprego em anos, enquanto `EMPLOYED_SPECIAL_VALUE` preserva a informação sobre os registros que possuíam o valor especial identificado em `DAYS_EMPLOYED`.

Dessa forma, as colunas originais e intermediárias relacionadas ao cálculo dessas variáveis foram removidas, reduzindo a redundância da base e evitando que múltiplas versões da mesma informação sejam utilizadas simultaneamente durante a modelagem.

Essa etapa contribui para simplificar a interpretação dos resultados e minimizar problemas de correlação entre atributos que representam essencialmente o mesmo fenômeno.
"""

df_model = df.drop(
    columns=[
        "DAYS_BIRTH",
        "DAYS_EMPLOYED",
        "DAYS_EMPLOYED_TREATED"
    ]
)

print("Formato da base para modelagem:")
print(df_model.shape)

print("\nValores ausentes:")
print(df_model.isna().sum().sort_values(ascending=False))

print(df_model.columns.tolist())

"""Embora tenham sido identificados valores elevados para quantidade de filhos e tamanho da família, a análise dos registros mostrou coerência entre as variáveis relacionadas.

Os clientes com maior quantidade de filhos também apresentaram tamanhos familiares compatíveis, não sendo observadas evidências claras de erros de preenchimento.

Dessa forma, optou-se por manter esses registros na base. Como representam uma parcela muito pequena da população e podem corresponder a situações reais, decidiu-se preservar a informação e avaliar posteriormente o comportamento dessas variáveis durante a modelagem.

## Avaliação das variáveis de contato

Antes da finalização da base para modelagem, foi realizada uma análise das variáveis relacionadas aos meios de contato dos clientes.

A coluna `FLAG_MOBIL` apresentou o mesmo valor para todos os registros da base. Como não existe variabilidade nessa variável, ela não possui capacidade de diferenciar clientes nem de contribuir para a construção de modelos preditivos. Por esse motivo, a coluna foi removida.

As variáveis `FLAG_WORK_PHONE`, `FLAG_PHONE` e `FLAG_EMAIL` apresentaram distribuição com valores distintos entre os clientes, indicando potencial informativo. Dessa forma, foram mantidas para as etapas posteriores de modelagem.
"""

df_model["FLAG_MOBIL"].value_counts(dropna=False)

df_model["FLAG_WORK_PHONE"].value_counts(dropna=False)

df_model["FLAG_PHONE"].value_counts(dropna=False)

df_model["FLAG_EMAIL"].value_counts(dropna=False)

df_model = df_model.drop(columns=["FLAG_MOBIL"])

print("Formato após remoção de FLAG_MOBIL:")
print(df_model.shape)

"""## Base final para modelagem

Após as etapas de limpeza, transformação e engenharia de atributos, foi obtida a base final utilizada nas etapas posteriores de modelagem.

Foram removidas variáveis redundantes derivadas do processo de tratamento, bem como a variável `FLAG_MOBIL`, que apresentou o mesmo valor para todos os registros e, portanto, não possuía capacidade de discriminar diferentes perfis de clientes.

A base final resultante possui 36.457 registros e 20 variáveis, sem valores ausentes e sem registros duplicados. Dessa forma, a base encontra-se consistente para utilização nos algoritmos de classificação.

A análise da variável alvo confirmou a presença de forte desbalanceamento entre as classes. Aproximadamente 98,31% dos clientes foram classificados como bons pagadores (`TARGET_BAD = 0`), enquanto apenas 1,69% foram classificados como maus pagadores (`TARGET_BAD = 1`).

Esse resultado será considerado durante a etapa de modelagem, uma vez que algoritmos treinados em bases altamente desbalanceadas podem apresentar dificuldade para identificar corretamente a classe minoritária.
"""

print("Formato final da base para modelagem:")
print(df_model.shape)

print("\nValores ausentes:")
print(df_model.isna().sum().sum())

print("\nIDs duplicados:")
print(df_model["ID"].duplicated().sum())

print("\nDistribuição da variável alvo:")
print(df_model["TARGET_BAD"].value_counts())

print("\nDistribuição percentual da variável alvo:")
print(
    (df_model["TARGET_BAD"]
     .value_counts(normalize=True) * 100)
    .round(2)
)

print("Formato final da base para modelagem:")
print(df_model.shape)

print("\nValores ausentes:")
print(df_model.isna().sum().sum())

print("\nIDs duplicados:")
print(df_model["ID"].duplicated().sum())

print("\nDistribuição da variável alvo:")
print(df_model["TARGET_BAD"].value_counts())

print("\nDistribuição percentual da variável alvo:")
print(
    (df_model["TARGET_BAD"]
     .value_counts(normalize=True) * 100)
    .round(2)
)

# Salvar CSV final
df_model.to_csv(
    "base_modelagem_final.csv",
    index=False
)

print("\n✅ Arquivo 'base_modelagem_final.csv' gerado com sucesso.")